name: upload

on:
  push:
    branches:
      - master

jobs:
  dev-deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: chrislennon/action-aws-cli@v1.1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        run: yarn
#      - name: lint
#        run: yarn lint
#      - name: tsc
#        run: yarn tsc TODO: add lint and tsc checks
      - name: build
        run: yarn build
      - name: upload
        run: aws s3 sync build/. s3://recap.dev/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id E14K1HSGKN0UVL --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
